### ISSUE TITLE
credentials file

### ISSUE THREAD

**Issue by MohdMusharraf** [themanvendra00/mailBot-NodeJs#1]
Can you tell me the format of the credentials.json file

**Comment by themanvendra00** [comment]
credentials.json

{
    "web": {
        "client_id": "<your client id>",
        "project_id": "<your project name>",
        "auth_uri": "<your auth uri>",
        "token_uri": "<token>",
        "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
        "client_secret": "<your secret>",
        "redirect_uris": [
            "http://localhost:3000/auth/callback"
        ]
    }
}

It might help!

**Comment by themanvendra00** [comment]
you can download your credentials.json file from google developer itself

**Comment by MohdMusharraf** [comment]
Did you also make this repo for the OpenInApp Software Engineering Challenge if yes then can you tell me about your experience.

**Comment by MohdMusharraf** [comment]
And the access is blocked how can I resolve that?

**Comment by themanvendra00** [comment]
> Did you also make this repo for the OpenInApp Software Engineering Challenge if yes then can you tell me about your experience?

It's an assignment(basically a hiring assignment) for Listed Inc. 
Talking about my experience, I'm an aspiring NodeJs developer.

**Comment by themanvendra00** [comment]
> And the access is blocked how can I resolve that?

Which access bro?
